# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [2]:
# %run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [3]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [4]:
np.__version__

'2.2.2'

#### 3. Create a null vector of size 10 (★☆☆)

In [5]:
arr = np.zeros(shape=(1,10))
arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

#### 4. How to find the memory size of any array (★☆☆)

In [6]:
# np.int32 uses 4 bytes (32 bits).
# np.int64 uses 8 bytes (64 bits).
# arr.nbytes
arr.size * arr.itemsize

80

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [7]:
# np.add?
help(np.add)

Help on ufunc in module numpy:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

    Add arguments element-wise.

    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [8]:
arr = np.zeros(shape=(10))
arr[4] = 1
arr

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [9]:
arr = np.arange(start=10,stop=50)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [10]:
a = arr[::-1]
print(a)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [11]:
arr = np.random.randint(low=10,high=100,size=30)
print(arr)
np.flip(arr)

[85 80 43 98 59 40 46 49 27 76 62 98 16 36 17 81 67 37 52 42 72 25 80 31
 22 99 24 24 74 11]


array([11, 74, 24, 24, 99, 22, 31, 80, 25, 72, 42, 52, 37, 67, 81, 17, 36,
       16, 98, 62, 76, 27, 49, 46, 40, 59, 98, 43, 80, 85], dtype=int32)

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [12]:
np.arange(start=0,stop=9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [13]:
arr = np.array([1,2,0,0,4,0,0])

In [14]:
arr.nonzero()

(array([0, 1, 4]),)

In [15]:
arr[arr.nonzero()]

array([1, 2, 4])

In [16]:
np.where(arr==0)

(array([2, 3, 5, 6]),)

In [104]:
arr = np.array([1,2,0,0,4,9,0])
print(np.where([arr>0,arr<0]))
arr[np.where([arr<0,arr>0])[1]]

(array([0, 0, 0, 0]), array([0, 1, 4, 5]))


array([1, 2, 4, 9])

#### 11. Create a 3x3 identity matrix (★☆☆)

In [18]:
np.identity(n=3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [19]:
# np.random.randint(size=27,low=0,high=100).reshape(3,3,3)
np.random.random((3,3,3))

array([[[0.51729446, 0.59632705, 0.69120986],
        [0.64535325, 0.04655796, 0.1483667 ],
        [0.41670661, 0.01847557, 0.61205796]],

       [[0.18082823, 0.21832077, 0.75764827],
        [0.7105762 , 0.03013179, 0.42309085],
        [0.12258785, 0.72278758, 0.76548606]],

       [[0.77945911, 0.16869284, 0.77704421],
        [0.07124925, 0.83301248, 0.11278877],
        [0.16645921, 0.65247756, 0.03063935]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [20]:
arr = np.random.randint(low=1,high=100,size=(10,10))
print(arr.min())
print(arr.max())

1
98


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [21]:
np.random.randint(low=10,high=100,size=30).mean()

np.float64(57.36666666666667)

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [22]:
arr = np.zeros(shape=(5,5),dtype=int)
arr[0,:] = 1
arr[:,0] = 1
arr[-1,:] = 1
arr[:,-1] = 1
arr

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [23]:
arr = np.arange(start=10,stop=35).reshape(5,5)
arr[0,:] = 0
arr[:,0] = 0
arr[-1,:] = 0
arr[:,-1] = 0
arr

array([[ 0,  0,  0,  0,  0],
       [ 0, 16, 17, 18,  0],
       [ 0, 21, 22, 23,  0],
       [ 0, 26, 27, 28,  0],
       [ 0,  0,  0,  0,  0]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [24]:
0 * np.nan

nan

In [25]:
np.nan == np.nan

False

In [26]:
np.inf > np.nan

False

In [27]:
np.inf - np.nan

nan

In [28]:
0.3 == 3 * 0.1

False

In [29]:
np.nan in set([np.nan])

True

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [30]:
arr = np.arange(start=10,stop=35).reshape(5,5)
for i in range(5):
    arr[i][i] = i+1
arr

array([[ 1, 11, 12, 13, 14],
       [15,  2, 17, 18, 19],
       [20, 21,  3, 23, 24],
       [25, 26, 27,  4, 29],
       [30, 31, 32, 33,  5]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [31]:
arr = np.zeros(shape=(8,8),dtype=int)
shape = arr.shape
shape
for i in range(shape[0]):
    for j in range(shape[1]):
        if i % 2 == 0:
            if j % 2 == 1:
                arr[i][j] = 1
        else:
            if j % 2 == 0:
                arr[i][j] = 1
arr

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [32]:
arr = np.arange(start=0,stop=(6*7*8)).reshape(6,7,8)
arr[1][5][3]

np.int64(99)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [33]:
a = [[0,1],[1,0]]
print(a)
np.tile(a,(4,4))

[[0, 1], [1, 0]]


array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [34]:
arr = np.arange(start=1,stop=26).reshape(5,5)
print(arr)
arr = (arr - arr.mean()) / arr.size
arr

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


array([[-0.48, -0.44, -0.4 , -0.36, -0.32],
       [-0.28, -0.24, -0.2 , -0.16, -0.12],
       [-0.08, -0.04,  0.  ,  0.04,  0.08],
       [ 0.12,  0.16,  0.2 ,  0.24,  0.28],
       [ 0.32,  0.36,  0.4 ,  0.44,  0.48]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [35]:
color_dtype = np.dtype([
    ('r', np.uint8),  # Red channel
    ('g', np.uint8),  # Green channel
    ('b', np.uint8),  # Blue channel
    ('a', np.uint8)   # Alpha channel (opacity)
])

# Example usage
color = np.array([(255, 128, 0, 255)], dtype=color_dtype)
color

array([(255, 128, 0, 255)],
      dtype=[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [36]:
arr1 = np.arange(start=1,stop=16).reshape(5,3)
arr2 = np.arange(start=20,stop=26).reshape(3,2)
np.matmul(arr1,arr2)

array([[136, 142],
       [334, 349],
       [532, 556],
       [730, 763],
       [928, 970]])

In [37]:
arr3 = np.zeros((arr1.shape[0],arr2.shape[1]),dtype=int)
row = arr1.shape[0]
col = arr2.shape[1]
steps = arr1.shape[1]
for i in range(row):
    for j in range(col):
        prod = 0
        for k in range(steps):
            prod += arr1[i][k] * arr2[k][j]
        arr3[i][j] = prod
arr3

array([[136, 142],
       [334, 349],
       [532, 556],
       [730, 763],
       [928, 970]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [38]:
arr = np.arange(start=1,stop=50)
print(arr)
arr[((arr>=3) & (arr<=8))] *= -1
arr

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49]


array([ 1,  2, -3, -4, -5, -6, -7, -8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [39]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9


10


In [40]:
for i in range(5):
    print(i)

0
1
2
3
4


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [41]:
np.array(8) ** np.array(8)

np.int64(16777216)

In [42]:
2 << np.array(3) >> 2

np.int64(4)

In [43]:
np.array(8) <- np.array(8)

np.False_

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [44]:
np.array(0) / np.array(0)

C:\Users\hibam\AppData\Local\Temp\ipykernel_17160\873513115.py:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)


np.float64(nan)

In [45]:
np.array(0) // np.array(0)

C:\Users\hibam\AppData\Local\Temp\ipykernel_17160\2018018105.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


np.int64(0)

In [46]:
np.array([np.nan]).astype(int)

C:\Users\hibam\AppData\Local\Temp\ipykernel_17160\3091100680.py:1: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int)


array([-9223372036854775808])

In [47]:
np.array([np.nan]).astype(int).astype(float)

C:\Users\hibam\AppData\Local\Temp\ipykernel_17160\699728972.py:1: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆)

In [48]:
arr = np.array([1.4,2.9,3.5,10.1],dtype=float)
arr = np.int64(arr)
arr

array([ 1,  2,  3, 10])

#### 30. How to find common values between two arrays? (★☆☆)

In [49]:
arr1 = np.arange(start=1,stop=10)
arr2 = np.arange(start=7,stop=20)
arr1,arr2

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]))

In [50]:
np.intersect1d(arr1,arr2)

array([7, 8, 9])

In [51]:
np.union1d(arr1,arr2)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [52]:
np.seterr(invalid='ignore')

{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}

In [53]:
np.array(0) / np.array(0)

np.float64(nan)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [54]:
np.emath.sqrt(-1)

np.complex128(1j)

In [55]:
np.sqrt(-1) == np.emath.sqrt(-1)

np.False_

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [56]:
np.datetime64('today','D')

np.datetime64('2025-02-05')

In [57]:
np.timedelta64(1,'D')

np.timedelta64(1,'D')

In [58]:
np.datetime64('today','D') - np.timedelta64(1,'D')

np.datetime64('2025-02-04')

In [59]:
np.datetime64('today','D') + np.timedelta64(1,'D')

np.datetime64('2025-02-06')

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [60]:
np.arange(start=np.datetime64('2016-07','D'),stop=np.datetime64('2016-08','D'),dtype='datetime64[D]')

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

In [61]:
date = np.datetime64('2024-07-30').astype('datetime64[D]').astype(int) % 7
date

np.int64(5)

In [62]:
np.datetime64('2024-07','D') - np.datetime64('2024-08','D')

np.timedelta64(-31,'D')

In [63]:
np.datetime64(0, 'Y')

np.datetime64('1970')

In [64]:
np.datetime64('2024-07','D')

np.datetime64('2024-07-01')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [65]:
arr1 = np.arange(start=10,stop=50,dtype=float)
arr2 = np.arange(start=30,stop=70)

In [66]:
arr1 += arr2
print(arr1)
arr1 *= -(arr1/2)
arr1

[ 40.  42.  44.  46.  48.  50.  52.  54.  56.  58.  60.  62.  64.  66.
  68.  70.  72.  74.  76.  78.  80.  82.  84.  86.  88.  90.  92.  94.
  96.  98. 100. 102. 104. 106. 108. 110. 112. 114. 116. 118.]


array([ -800.,  -882.,  -968., -1058., -1152., -1250., -1352., -1458.,
       -1568., -1682., -1800., -1922., -2048., -2178., -2312., -2450.,
       -2592., -2738., -2888., -3042., -3200., -3362., -3528., -3698.,
       -3872., -4050., -4232., -4418., -4608., -4802., -5000., -5202.,
       -5408., -5618., -5832., -6050., -6272., -6498., -6728., -6962.])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [67]:
arr = np.arange(start=-10,stop=20)
print(arr[arr>=0])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [68]:
np.extract(arr>0,arr)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [69]:
np.compress(arr>0,arr)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [70]:
arr[~(arr<0)]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [71]:
arr

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,
         3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,  14,  15,
        16,  17,  18,  19])

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [72]:
np.arange(5).reshape(1, 5)

array([[0, 1, 2, 3, 4]])

In [73]:
np.zeros((5, 1),dtype=int)

array([[0],
       [0],
       [0],
       [0],
       [0]])

In [74]:
np.arange(5).reshape(1, 5) + np.zeros((5, 1),dtype=int)

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [75]:
np.tile(np.arange(5),(5,1))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [76]:
arr = np.arange(5).reshape(1,5)
print(arr)
np.repeat(arr,axis=0,repeats=5)

[[0 1 2 3 4]]


array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [77]:
np.array(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [78]:
np.linspace(0,1,12)[1:-1]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [79]:
a = np.random.randint(low=10,high=100,size=10)
a.sort()
print(a)

[29 30 42 50 62 71 73 86 87 92]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [80]:
np.arange(start=10,stop=20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [81]:
sum(np.arange(start=10,stop=20))

np.int64(145)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [82]:
a = np.arange(start=10,stop=20)
b = np.arange(start=11,stop=21)

all(a == b)

np.False_

In [83]:
np.array_equal(a,b)

False

#### 43. Make an array immutable (read-only) (★★☆)

In [84]:
arr = np.array([1, 2, 3, 4, 5])
arr.flags.writeable = False
# arr[0] = 9 # it will show an error

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [85]:
cartesian_coords = np.random.rand(10, 2) * 10
print(cartesian_coords)
x = cartesian_coords[:, 0]
y = cartesian_coords[:, 1]

polar_coords = np.row_stack((x,y))
polar_coords

[[1.01348819 2.7685914 ]
 [3.11183622 7.5343691 ]
 [8.94255223 5.80573909]
 [7.01186793 1.11901952]
 [8.9336776  2.26392722]
 [0.74150657 8.64392357]
 [0.39581186 4.97853028]
 [7.09863764 9.79391015]
 [4.85744786 1.13505096]
 [9.99193007 0.32433251]]


C:\Users\hibam\AppData\Local\Temp\ipykernel_17160\709850599.py:6: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  polar_coords = np.row_stack((x,y))


array([[1.01348819, 3.11183622, 8.94255223, 7.01186793, 8.9336776 ,
        0.74150657, 0.39581186, 7.09863764, 4.85744786, 9.99193007],
       [2.7685914 , 7.5343691 , 5.80573909, 1.11901952, 2.26392722,
        8.64392357, 4.97853028, 9.79391015, 1.13505096, 0.32433251]])

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [86]:
arr = np.arange(start=10,stop=50)
arr[np.where(arr == arr.max())] = 0
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48,  0])

In [87]:
arr[arr == arr.max()] = 0
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47,  0,  0])

In [88]:
arr[arr==arr.max()] = 0
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46,  0,  0,  0])

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

In [89]:
arr = np.arange(start=10,stop=50)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [90]:
scaler = 17.55
arr[np.abs(scaler - arr).argmin()]

np.int64(18)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [91]:
arr = np.array([1.5, 2.8, 3.1, 4.7], dtype=np.float32)

arr[:] = arr.astype(np.int32)

print(arr)

[1. 2. 3. 4.]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [92]:
arr = np.array([[10, 20, 30, 40]])
for i,v in np.ndenumerate(arr):
    print(i,v)

(0, 0) 10
(0, 1) 20
(0, 2) 30
(0, 3) 40


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [93]:
np.random.normal(size=(10,2))

array([[-0.71957959,  1.39182962],
       [ 1.83882299,  1.77439865],
       [-1.41447472, -1.18345082],
       [-1.55572849, -0.28469259],
       [-1.02630132, -1.96423573],
       [-0.4703794 , -1.85017142],
       [-0.1962663 ,  0.11652917],
       [-0.15935467,  0.00409748],
       [-0.10387279, -0.10379579],
       [ 0.55161016, -0.16413923]])

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [94]:
rows, cols = 5, 5
p = 5

arr = np.zeros((rows, cols), dtype=int)
choices = np.random.choice(arr.size,size=p,replace=False)
row,col = np.unravel_index(choices,shape=arr.shape)
arr[row,col] = 1
arr

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 1, 0, 1],
       [0, 1, 0, 0, 0],
       [0, 1, 0, 0, 1]])

#### 58. Subtract the mean of each row of a matrix (★★☆)

In [95]:
arr = np.arange(start=10,stop=50,dtype=float).reshape(5,8)
print(arr)
m = arr.mean(axis=1)
print(m)
for i in range(arr.shape[0]):
    arr[i] -= m[i]
print(arr)

[[10. 11. 12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23. 24. 25.]
 [26. 27. 28. 29. 30. 31. 32. 33.]
 [34. 35. 36. 37. 38. 39. 40. 41.]
 [42. 43. 44. 45. 46. 47. 48. 49.]]
[13.5 21.5 29.5 37.5 45.5]
[[-3.5 -2.5 -1.5 -0.5  0.5  1.5  2.5  3.5]
 [-3.5 -2.5 -1.5 -0.5  0.5  1.5  2.5  3.5]
 [-3.5 -2.5 -1.5 -0.5  0.5  1.5  2.5  3.5]
 [-3.5 -2.5 -1.5 -0.5  0.5  1.5  2.5  3.5]
 [-3.5 -2.5 -1.5 -0.5  0.5  1.5  2.5  3.5]]


#### 59. How to sort an array by the nth column? (★★☆)

In [96]:
arr[:,2]

array([-1.5, -1.5, -1.5, -1.5, -1.5])

In [97]:
arr = np.array([[4, 2, 8],[1, 5, 9],[3, 7, 6]])
print(arr)
arr[arr[0].argsort()]

[[4 2 8]
 [1 5 9]
 [3 7 6]]


array([[1, 5, 9],
       [4, 2, 8],
       [3, 7, 6]])

#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [98]:
# arr = np.random.randint(low=0,high=1,size=(5,5))
arr = np.array([[0, 1, 0],
                [0, 0, 0],
                [9, 2, 0]])
print(arr)
null_columns = np.all(arr == 0, axis=0)
print(null_columns)
arr[:,null_columns]

[[0 1 0]
 [0 0 0]
 [9 2 0]]
[False False  True]


array([[0],
       [0],
       [0]])

#### 61. Find the nearest value from a given value in an array (★★☆)

In [99]:
arr = np.array([[0, 1, 5],
                [7, 8, 0],
                [9, 2, 4]])
value = 10
idx = np.abs(value - arr).argmin()
print(idx)
row,col = np.unravel_index(idx,arr.shape)
print(row,col)
arr[row][col]

6
2 0


np.int64(9)

In [100]:
index = 5
shape = (3, 4)
print(np.unravel_index(index, shape, order='C'))

(np.int64(1), np.int64(1))


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [101]:
arr1 = np.random.randint(low=10,high=100,size=(1,3))
arr2 = np.random.randint(low=10,high=100,size=(3,1))
# print(arr1)
# print(arr2)
for i in range(arr1.shape[1]):
    print(arr1[0][i] + arr2[i][0])

110
150
155


#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [102]:
vector = np.array([1, 2, 3, 4, 5])
indices = np.array([0, 1, 1, 3, 3, 3])
np.add.at(vector,indices,1)
vector

array([2, 4, 3, 7, 5])

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [103]:
X = np.array([1, 2, 3, 4, 5])
I = np.array([0, 1, 1, 3, 3])
F = np.zeros(5)
np.add.at(F,I,X)
F

array([1., 5., 0., 9., 0.])

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)