In [2]:
%pip install numpy


Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.2 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
import numpy as np

print(np.__version__)

2.2.2


# creating array in numpy

In [4]:
import numpy as np
data=[1,2,3,456,8]
array=np.array(data)
print(array)

[  1   2   3 456   8]


In [5]:
# converting touple into array
np.array((1,2,3,56))

array([ 1,  2,  3, 56])

In [6]:
print(type(array))

<class 'numpy.ndarray'>


# creating 2-D array

In [7]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


# 3-D array

In [8]:
arr=np.array([[[1,2,3],[4,2,5]],[[7,5,3],[9,5,1]]])
print(arr)

# printing the dimension 
print(arr.ndim)

[[[1 2 3]
  [4 2 5]]

 [[7 5 3]
  [9 5 1]]]
3


# creating the array while giving the dimension when writing the code

In [9]:
arr=np.array([1,2,3,41],ndmin=5)
print(arr)
print(arr.ndim)

[[[[[ 1  2  3 41]]]]]
5



# accessing elements in 1D


### single element

In [10]:
arr=np.array((10,2,3,4,5,6))
print(arr[0])

10


### multiple elements

In [11]:
print(arr[1],arr[4])

2 5


### sum of two numbers

In [12]:
print(arr[1]+arr[4])

7


# accessing elements in 2D

### single element


In [13]:
arr=np.array([[5,3,11],[12,345,89]])
print(arr[1,0]) #first element from the second array

print(arr[0,2]) # third element from the first array

12
11


# accessing elements in 3D

### single element

In [14]:
arr1=np.array([[[1,2,5],[51,86,23]],[[12,13,15],[75,65,3]]])
print(arr1[1,0,2])
# third element in the first array in the second array

15



# negative indexing

In [15]:
# for accessing elements from the end
arr=np.array([4,2,3,8,33,25,12,13,14,15,16])
print(arr[-1])

16


# slicing 1D

In [16]:
print(arr[0:2])
print(arr[:3])
print(arr[1:])
print(arr[1:6:2]) #index 1 -6 with step=2
print(arr[-3:-1])
print(arr[::2])

[4 2]
[4 2 3]
[ 2  3  8 33 25 12 13 14 15 16]
[ 2  8 25]
[14 15]
[ 4  3 33 12 14 16]


# slicing 2D

In [17]:
arr1=np.array([[1,2,5],[51,86,23]])
print(arr1[1,0:2])

[51 86]


In [18]:
import numpy as np
arr=np.zeros(shape=(1,10))
arr1=np.zeros(shape=(2,10))
print('1D:',arr)

print('2D:',arr1)

1D: [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
2D: [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


# creating an array of ones

In [19]:
import numpy as np
arr=np.ones((3,3))
arr

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

# Linear algebra

In [20]:
A=np.array([[1,2],[3,4]])
B=np.array([1,2])

# Matrix addition
A+B

# Matrix substraction
A-B

# Matrix multiplication
A*B

# Dot product
C=np.dot(A,B)
C
D=A@B
D

# transpose
tr=A.T
tr

# Determinant
det_A=np.linalg.det(A)
det_A

# inverse of a matrix
inv_A=np.linalg.inv(A)
inv_A

# eigen values and vectors
eigenval,eigenvec=np.linalg.eig(A)
eigenval
eigenvec

# solving 
x=np.linalg.solve(A,B)
x

# norms of a vector
L2_norm=np.linalg.norm(A)
L1_norm=np.linalg.norm(A,ord=1)
L2_norm
L1_norm


# trace 
trace_A=np.trace(A)
trace_A

np.int64(5)

In [29]:
arr11=np.arange(start=0,stop=25).reshape(5,5)
arr11[arr11<5]=111
arr11


array([[111, 111, 111, 111, 111],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24]])

In [30]:
arr12=np.delete(arr11,1,0)
arr12

array([[111, 111, 111, 111, 111],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24]])

In [31]:
arr13=np.delete(arr11,0,axis=1)
arr13

array([[111, 111, 111, 111],
       [  6,   7,   8,   9],
       [ 11,  12,  13,  14],
       [ 16,  17,  18,  19],
       [ 21,  22,  23,  24]])

In [33]:
np.fill_diagonal(arr13,[123])
arr13

array([[123, 111, 111, 111],
       [  6, 123,   8,   9],
       [ 11,  12, 123,  14],
       [ 16,  17,  18, 123],
       [ 21,  22,  23,  24]])

# print all even numbers till 100

In [34]:
arr=np.arange(2,100,2)
arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68,
       70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

# odd numbers

In [35]:
arr=np.arange(1,100,2)
arr

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

# multiple of 3

In [36]:
arr=np.arange(0,100,3)
arr

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

# maximum and minimum value along an axis


In [38]:
arr=np.array([[1,2,13],[4,1,3]])

print(np.max(arr,axis=0)) #max of each column

# maximum of each column
print(np.max(arr,axis=1))

[ 4  2 13]
[13  4]
