In [1]:
import numpy as np

# Arrays and Operations
### Array Creation

In [2]:
array = np.arange(1,11).reshape(2,5)
print(array)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [3]:
print(np.eye(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [4]:
a20 = np.zeros(shape=(5,5))
np.fill_diagonal(a20,1)
a20

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### Array Slicing

In [5]:
a = np.array([1,2,3,4,5,6,7,8,9])
print(a[3:6])

[4 5 6]


In [6]:
a1 = np.arange(1,10)
print(a1[3:6])

[4 5 6]


### Element-wise Operations

In [7]:
a2 = np.array([1,2,3])
a3 = np.array([4,5,6])

#Addition
print(a2+a3)

[5 7 9]


In [8]:
print(a3-a2)

[3 3 3]


In [9]:
print(a2*a3)

[ 4 10 18]


In [10]:
print(np.dot(a2,a3))

32


### Concatenation

In [11]:
a2
a3
print(np.concatenate((a2,a3)))

[1 2 3 4 5 6]


### Boolean Masking

In [12]:
a1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
print(a1>4)

print(a1[a1>4])

[False False False False  True  True  True  True  True]
[5 6 7 8 9]


# Broadcasting
### Rules

In [14]:
#THEORY

### Example

In [15]:
a4 = np.array([[1],[2],[3]])  #(3,1)
a5 = np.array([[10,20,30,40]])   #(1,4)

print(a4+a5) #(3,4)

[[11 21 31 41]
 [12 22 32 42]
 [13 23 33 43]]


In [16]:
#To add a one-dimensional array to each row
a6 = np.array([[1,2,3], [4,5,6]])
a7 = np.array([10,20,30])

print(a6+a7)

[[11 22 33]
 [14 25 36]]


### Adding a scalar to a multi-dimensional array

In [17]:
a6
scalar=10

In [18]:
print(a6+scalar)

[[11 12 13]
 [14 15 16]]


# Linear Algebra
### Matrix Multiplication

In [19]:
a6 = np.array([[1,2,3], [4,5,6]])

a8 = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(np.dot(a6,a8))

[[30 36 42]
 [66 81 96]]


In [20]:
a6

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print(np.dot(A,B))

[[19 22]
 [43 50]]


In [22]:
print(A@B)

[[19 22]
 [43 50]]


### Transpose

In [23]:
#Using .T
import numpy as np

arr = np.array([[1, 2], [3, 4], [5, 6]])

transposed_arr = arr.T
print(transposed_arr)


[[1 3 5]
 [2 4 6]]


In [24]:
#Using .transpose()
import numpy as np

arr = np.array([[1, 2], [3, 4], [5, 6]])

transposed_arr = arr.transpose()
print(transposed_arr)


[[1 3 5]
 [2 4 6]]


In [25]:
#on higher dimensional arrays
arr3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

transposed_arr3d = arr3d.transpose()
print(transposed_arr3d)


[[[1 5]
  [3 7]]

 [[2 6]
  [4 8]]]


### Determinant (only for square matrix)

In [26]:
import numpy as np

square_matrix = np.array([[1, 2],
                       [3, 4]])

# Calculate the determinant
det = np.linalg.det(square_matrix)

print("Determinant of the 2x2 matrix:", det)


Determinant of the 2x2 matrix: -2.0000000000000004


### Eigenvalues & Eigenvectors

In [28]:
a9 = np.array([[4,-2], [1,1]])
eigenvalues,eigenvectors=np.linalg.eig(a9)

print("Eigenvalue:\n", eigenvalues)
print("Eigenvectors:\n",eigenvectors)


Eigenvalue:
 [3. 2.]
Eigenvectors:
 [[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


### Solving Linear Equations

In [371]:
A = np.array([[3, 1], [1, 2]])
B = np.array([9, 8])

x = np.linalg.solve(A,B)
print(x)

[2. 3.]


# Array Manipulation
### Reshaping

In [192]:
a10 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
a10.reshape(2,3,2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

### Flattening

In [391]:
a11 = np.array([[1,2,3], [4,5,6]])

print("Flattened:",a11.flatten()) #Creates copy
print("Ravel:",a11.ravel()) #Creates view

Flattened: [1 2 3 4 5 6]
Ravel: [1 2 3 4 5 6]


### Stacking

In [194]:
a12 = np.array([1,2,3])
a13 = np.array([4,5,6])

In [195]:
print(np.vstack((a12,a13)))

[[1 2 3]
 [4 5 6]]


In [196]:
print(np.hstack((a12,a13)))

[1 2 3 4 5 6]


### Splliting

In [197]:
a10

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [198]:
print(np.split(a10,3))

[array([1, 2, 3, 4]), array([5, 6, 7, 8]), array([ 9, 10, 11, 12])]


### Adding and Removing Dimensions

In [373]:
#Adding
import numpy as np

arr = np.array([1, 2, 3])

arr_2d = np.expand_dims(arr, axis=0) 
print("Array with added dimension (axis=0):\n", arr_2d)

arr_2d_col = np.expand_dims(arr, axis=1) 
print("Array with added dimension (axis=1):\n", arr_2d_col)


Array with added dimension (axis=0):
 [[1 2 3]]
Array with added dimension (axis=1):
 [[1]
 [2]
 [3]]


In [382]:
#Removing
import numpy as np


arr_2d = np.array([[[1, 2, 3]]])

arr_squeezed = np.squeeze(arr_2d)
print("Array with dimension removed:\n", arr_squeezed)

print(arr_2d.ndim)

print(arr_squeezed.ndim)


Array with dimension removed:
 [1 2 3]
3
1


# Statistical Functions
### Measures of central tendencies

In [199]:
#Mean, Median, Mode
a10

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [202]:
print("Mean:",np.mean(a10))
print("Median:",np.median(a10))

Mean: 6.5
Median: 6.5


### Percentile

In [204]:
a10

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [216]:
print(np.percentile(a10,25))
print(np.percentile(a10,50))
print(np.percentile(a10,75))


3.75
6.5
9.25


### Measures of Dispersion

In [218]:
print(np.var(a10))

11.916666666666666


In [220]:
print(np.std(a10))

3.452052529534663


# Random Sampling
### Random Array Generation

In [229]:
a14 = np.random.rand(2,3)
print(a14)

[[0.92786817 0.23018491 0.20481568]
 [0.35408827 0.57420469 0.59651446]]


In [231]:
a15 = np.random.randn(2,3)
print(a15)

[[-0.50657451 -0.55989983 -0.59756458]
 [ 1.30711254 -1.04546461  0.84921569]]


In [395]:
a16 = np.random.randint(1,10, size=(2,3))
print(a16)

[[9 3 4]
 [5 5 6]]


In [396]:
#Choice
a17 = np.array([1,2,3,4,5])
array = np.random.choice(a17, size=3)
print(array)

[4 2 3]


In [402]:
a25 = np.random.randint(1,11,15)
array = np.random.choice(a25, size=5)
print(array)

[ 8 10  5  8 10]


In [297]:
#Seed
np.random.seed(11)
a18 = np.random.randint(1,20, size=(2,3))
a18


#Good for reproducibility

array([[17, 18, 14],
       [13,  2,  8]])

### Sampling from a Distribution

In [301]:
a19 = np.random.normal(loc=5, scale=2, size=10)  #loc-mean, scale-SD
print(a19)

[4.3031485  3.54559005 5.94440779 3.75252608 3.96957716 7.11074577
 3.57641386 4.33574615 5.47376074 4.07342437]


# ----------------------------

## Qs
### Extract all the even indexed elements

In [327]:
a10
print("Even indexed elements: ", a10[::2])

Even indexed elements:  [ 1  3  5  7  9 11]


### Extract last 2 rows and First 2 cols

In [58]:
import numpy as np
a21 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print(a21[2:, :2])

[[ 9 10]
 [13 14]]


In [342]:
a22 = np.array([[0, 7, 1, 3, 4],
 [110, 1, 190, 670, 7],
 [6, 9, 46, 4, 4],
 [7, 5, 1, 59, 8],
 [1, 780, 7, 3, 6]])
a22

array([[  0,   7,   1,   3,   4],
       [110,   1, 190, 670,   7],
       [  6,   9,  46,   4,   4],
       [  7,   5,   1,  59,   8],
       [  1, 780,   7,   3,   6]])

In [345]:
a22[a22>10] = 0
a22

array([[0, 7, 1, 3, 4],
       [0, 1, 0, 0, 7],
       [6, 9, 0, 4, 4],
       [7, 5, 1, 0, 8],
       [1, 0, 7, 3, 6]])

### Swap rows

In [ ]:
a23 = np.array([[1,2],[3,4]])
a23 = a23[::-1]
print(a23)

array([[3, 4],
       [1, 2]])

### Find indices of elements greater than a number

In [ ]:
a24 = np.array([10,20,30,40,50,60,70,80,90])
print(np.where(a24>50))

[60 70 80 90]
