In [2]:
import numpy as np

In [3]:
arr1=np.full((2,3),7)
arr1

array([[7, 7, 7],
       [7, 7, 7]])

In [4]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([2,3,5,6,4])

print(arr1+arr2)
print(arr1**2)

[ 3  5  8 10  9]
[ 1  4  9 16 25]


In [5]:
print(np.median(arr1))

3.0


In [6]:
angles=np.array([0,30,45,60,180])
radians=np.deg2rad(angles)


In [7]:
print(np.sin(radians))
print(np.cos(radians))
print(np.tan(radians))

[0.00000000e+00 5.00000000e-01 7.07106781e-01 8.66025404e-01
 1.22464680e-16]
[ 1.          0.8660254   0.70710678  0.5        -1.        ]
[ 0.00000000e+00  5.77350269e-01  1.00000000e+00  1.73205081e+00
 -1.22464680e-16]


In [8]:
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

In [9]:
print(np.dot(A,B))
A@B

[[19 22]
 [43 50]]


array([[19, 22],
       [43, 50]])

In [10]:
A.T

array([[1, 3],
       [2, 4]])

In [11]:
print(np.linalg.det(A))

-2.0000000000000004


In [12]:
print(np.linalg.inv(A))

[[-2.   1. ]
 [ 1.5 -0.5]]


In [13]:
A = np.array([[3, 1],
              [1, 2]])

b = np.array([9, 8])

In [14]:
x=np.linalg.solve(A,b)
x

array([2., 3.])

In [15]:
data = np.random.randint(0, 100, size=20)
hist, bins = np.histogram(data, bins=5)
print("Bins:", bins)
print("Frequency:", hist)

Bins: [ 4.  22.4 40.8 59.2 77.6 96. ]
Frequency: [3 6 2 4 5]


In [16]:
print(data)

[38 26 40 26 50 68 87 44 78  4 13 86 34 86 77 22 67 28 96 71]


In [17]:
np.random.seed(72)  # Set seed for reproducibility
print(np.random.randint(1, 10, size=5))

[9 4 6 6 8]


In [18]:
arr = ['apple', 'banana', 'cherry']
print(np.random.choice(arr))  # Randomly pick one element
print(np.random.choice(arr, size=5, replace=True))  # Random sample with replacement

banana
['banana' 'banana' 'apple' 'apple' 'apple']


In [19]:
arr = np.array([1, 2, 3, 4, 5])

print(np.any(arr > 4))  # True (at least one element > 4)
print(np.all(arr > 0))  # True (all elements > 0)

True
True


In [20]:
arr = np.array([10, 20, 30, 40, 50])
new_arr = np.where(arr > 25, "High", "Low")
print(new_arr)
# Output: ['Low' 'Low' 'High' 'High' 'High']

['Low' 'Low' 'High' 'High' 'High']


In [21]:
arr = np.array([10, 20, 30, 40, 50])
filtered = arr[arr > 25]  # Keep values greater than 25
print(filtered)
# Output: [30 40 50]

[30 40 50]


In [22]:
arr = np.array([1, 2, 3, 4, 5])
bool_arr = arr > 2  # Condition check
print(bool_arr)
# Output: [False False  True  True  True]

[False False  True  True  True]


In [23]:
import pandas as pd
data={
    'Name':['Althaf','shahin'],
    'Age':[23,25]
}
df=pd.DataFrame(data)

Algorithm learning

In [24]:
#Linear regression
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import  mean_absolute_error,mean_squared_error,r2_score
import numpy as np

data=load_iris()
X=data.data
y=data.target

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

model=LinearRegression()
model.fit(X_train,y_train)

y_pred=model.predict(X_test)

print('MAS: ',mean_absolute_error(y_test,y_pred))
print('MES: ',mean_squared_error(y_test,y_pred))
print('RMSE: ',np.sqrt(mean_squared_error(y_test,y_pred)))
print('R2:',r2_score(y_test,y_pred))

MAS:  0.14637694965308523
MES:  0.037113794407976845
RMSE:  0.19264940801356448
R2: 0.9468960016420045


In [25]:
# logistic regression
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,precision_score,f1_score,recall_score

data=load_iris()
X=data.data
y=data.target

# Convert to binary classification: class 0 vs others
y_binary=(y==0).astype(int)

X_train,X_test,y_train,y_test=train_test_split(X,y_binary,test_size=0.2,random_state=42)

model=LogisticRegression()
model.fit(X_train,y_train)

y_pred=model.predict(X_test)

print('Accuracy:',accuracy_score(y_test,y_pred))
print('precision:',precision_score(y_test,y_pred))
print('recall:',recall_score(y_test,y_pred))
print('F1-score:',f1_score(y_test,y_pred))


Accuracy: 1.0
precision: 1.0
recall: 1.0
F1-score: 1.0


# Numpy problems

### NumPy Problems

1. **Array Creation and Manipulation**
    - Create a 3D array of shape (2, 3, 4) filled with random integers between 1 and 100.
    - Reshape the array to (4, 6) and print the result.
    - Extract the first two rows and last two columns from the reshaped array.
    1. **Mathematical Operations**
    - Given two arrays `A = np.array([[1, 2], [3, 4]])` and `B = np.array([[5, 6], [7, 8]])`, compute the matrix multiplication of `A` and `B`.
    - Compute the element-wise product of `A` and `B`.
    - Calculate the mean, standard deviation, and variance of the resulting matrix from the matrix multiplication.
2. **Statistical Functions**
    - Create a 1D array of 100 random numbers from a normal distribution with mean 0 and standard deviation 1.
    - Compute the mean, median, standard deviation, and variance of the array.
    - Find the minimum and maximum values in the array.

In [26]:
import numpy as np

array3D=np.random.randint(1,101,size=(2,3,4))
print("original array: ",array3D)

array_reshaped=array3D.reshape(4,6)
print('reshaped array: ', array_reshaped)

extracted=array_reshaped[:2,-2:]
print("First two rows and last two columns: ",extracted)

original array:  [[[73 29 54 66]
  [27 65 72 97]
  [35 62 53 32]]

 [[ 3 68 16 98]
  [96 55 18 95]
  [73 45 52 22]]]
reshaped array:  [[73 29 54 66 27 65]
 [72 97 35 62 53 32]
 [ 3 68 16 98 96 55]
 [18 95 73 45 52 22]]
First two rows and last two columns:  [[27 65]
 [53 32]]


In [34]:
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])

C=np.dot(A,B)
print(C) # matrix multiplication

print(A*B) # element wise

print(np.mean(C))
print(np.std(C))
print(np.var(C))


[[19 22]
 [43 50]]
[[ 5 12]
 [21 32]]
33.5
13.275918047351754
176.25


In [41]:
import matplotlib.pyplot as plt
np.random.seed(42) # to make random number fixed
array_1D=np.random.randn(100)
print(array_1D)

print(np.mean(array_1D))
print(np.median(array_1D))
print(np.std(array_1D))
print(np.var(array_1D))

print(np.max(array_1D))
print(np.min(array_1D))


[ 0.49671415 -0.1382643   0.64768854  1.52302986 -0.23415337 -0.23413696
  1.57921282  0.76743473 -0.46947439  0.54256004 -0.46341769 -0.46572975
  0.24196227 -1.91328024 -1.72491783 -0.56228753 -1.01283112  0.31424733
 -0.90802408 -1.4123037   1.46564877 -0.2257763   0.0675282  -1.42474819
 -0.54438272  0.11092259 -1.15099358  0.37569802 -0.60063869 -0.29169375
 -0.60170661  1.85227818 -0.01349722 -1.05771093  0.82254491 -1.22084365
  0.2088636  -1.95967012 -1.32818605  0.19686124  0.73846658  0.17136828
 -0.11564828 -0.3011037  -1.47852199 -0.71984421 -0.46063877  1.05712223
  0.34361829 -1.76304016  0.32408397 -0.38508228 -0.676922    0.61167629
  1.03099952  0.93128012 -0.83921752 -0.30921238  0.33126343  0.97554513
 -0.47917424 -0.18565898 -1.10633497 -1.19620662  0.81252582  1.35624003
 -0.07201012  1.0035329   0.36163603 -0.64511975  0.36139561  1.53803657
 -0.03582604  1.56464366 -2.6197451   0.8219025   0.08704707 -0.29900735
  0.09176078 -1.98756891 -0.21967189  0.35711257  1

### pandas Problems

1. **Data Loading and Exploration**
    - Load the Iris dataset from Seaborn and display the first 5 rows.
    - Display the summary statistics of the dataset using `describe()`.
    - Check for missing values in the dataset.
2. **Data Cleaning and Manipulation**
    - Load the Titanic dataset from Seaborn.
    - Handle missing values in the `age` column by filling them with the median age.
    - Drop rows where the `embarked` column has missing values.
    - Convert the `sex` column to numerical values (0 for male, 1 for female).
3. **Data Filtering and Grouping**
    - Filter the Titanic dataset to include only rows where `age` is greater than 30.
    - Group the dataset by `sex` and calculate the mean age for each group.
    - Merge the Titanic dataset with another dataset containing passenger names and additional information (create a sample dataset for this purpose).

In [47]:
import pandas as pd
import seaborn as sns
df=sns.load_dataset('iris')
print(df.head())
print(df.describe())
print(df.isnull().sum())

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa
       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000
sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
spec

In [ ]:
Titanic=sns.load_dataset('titanic')
print(Titanic.head())

meadian_age=Titanic['age'].median()
Titanic['age']=Titanic['age'].fillna(meadian_age)

Titanic=Titanic.dropna(subset=['embarked'])

Titanic['sex']=Titanic['sex'].map({'male':0,'female':1})

print("\nTitanic dataset after cleaning:")
print(Titanic.head())






   survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True  

Titanic dataset after cleaning:
   survived  pclass  sex   age  sibsp  parch     fare embarked  class    who  \
0         0       3    0  22.0      1      0   7.2500        S  Third    man   
1         1       1    1  

In [59]:
Titanic_30=Titanic[Titanic['age']>30]
print(Titanic_30.head())

calculate_mean_age=Titanic.groupby('sex')['age'].mean()
print(calculate_mean_age)

additional_info = pd.DataFrame({
    'passenger_id': [1, 2, 3, 4, 5],
    'passenger_name': ['John Doe', 'Jane Smith', 'Alice Brown', 'Bob White', 'Charlie Black'],
    'country': ['USA', 'UK', 'Canada', 'Australia', 'Ireland']
})

Titanic['passenger_id'] = range(1, len(Titanic) + 1) # cresting a fake passenger id

merged_df=pd.merge(Titanic,additional_info,on='passenger_id',how='left')

print("\nMerged Dataset:")
print(merged_df.head(10))

    survived  pclass  sex   age  sibsp  parch     fare embarked  class    who  \
1          1       1    1  38.0      1      0  71.2833        C  First  woman   
3          1       1    1  35.0      1      0  53.1000        S  First  woman   
4          0       3    0  35.0      0      0   8.0500        S  Third    man   
6          0       1    0  54.0      0      0  51.8625        S  First    man   
11         1       1    1  58.0      0      0  26.5500        S  First  woman   

    adult_male deck  embark_town alive  alone  passenger_id  
1        False    C    Cherbourg   yes  False             2  
3        False    C  Southampton   yes  False             4  
4         True  NaN  Southampton    no   True             5  
6         True    E  Southampton    no   True             7  
11       False    C  Southampton   yes   True            12  
sex
0    30.140676
1    27.788462
Name: age, dtype: float64

Merged Dataset:
   survived  pclass  sex   age  sibsp  parch     fare embarked  